{% set name = "perl-test-harness" %}
{% set version = "3.46" %}
{% set sha256 = "4c9e2e704035fc290695fa2ab0db3570715ed1aaadb061423564bc5365f47813" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/Test-Harness-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Test::Harness

about:
  home: https://metacpan.org/dist/Test-Harness
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: Run Perl standard test scripts with statistics
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
